name: Deploy to GKE
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      project_id: 
        required: true
      gke_sa_email: 
        required: true
      gcp_wif:
        required: true

env:
  GKE_CLUSTER: multi-cluster
  GKE_ZONE: europe-west1-b 

jobs:
  setup-build-push-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Authenticate gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF }}
          service_account: ${{ secrets.GKE_SA_EMAIL }}

      - name: Set up gcloud CLI components (kubectl , SDK, ...)
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker to use gcloud CLI
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy K8s files to GKE
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=natwimt/mutli-client:${{ github.run_number }}
          kubectl set image deployments/server-deployment server=natwimt/mutli-server:${{ github.run_number }}
          kubectl set image deployments/worker-deployment worker=natwimt/mutli-worker:${{ github.run_number }}
          kubectl get pods -o wide