name: Build and Deploy to GKE
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GKE_CLUSTER: multi-cluster
  GKE_ZONE: europe-central2-a   

jobs:
  setup-build-push-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        include:
         - context: ./client
           tag: natwimt/multi-client
           cache-from: type=local,src=/tmp/.buildx-cache/client
           cache-to: type=local,dest=/tmp/.buildx-cache-new/client

         - context: ./server
           tag: natwimt/multi-server
           cache-from: type=local,src=/tmp/.buildx-cache/server
           cache-to: type=local,dest=/tmp/.buildx-cache-new/server

         - context: ./nginx
           tag: natwimt/multi-nginx
           cache-from: type=local,src=/tmp/.buildx-cache/nginx
           cache-to: type=local,dest=/tmp/.buildx-cache-new/nginx

         - context: ./worker
           tag: natwimt/multi-worker
           cache-from: type=local,src=/tmp/.buildx-cache/worker
           cache-to: type=local,dest=/tmp/.buildx-cache-new/worker

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Authenticate gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/228935338518/locations/global/workloadIdentityPools/multi-k8s-wif/*
          service_account: ${{ secrets.GKE_SA_EMAIL}}

      - name: Set up gcloud CLI components (kubectl , SDK, ...)
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker to use gcloud CLI
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Build & test client docker dev image
        run: |
          docker build -t natwimt/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true natwimt/react-test npm test -- --coverage

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.context }}
          tags: ${{ matrix.tag }}:${{ github.run_number }}
          cache-to: ${{ matrix.cache-to }}
          cache-from: ${{ matrix.cache-from }}

      - name: Deploy K8s files to GKE
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=natwimt/mutli-client:${{ github.run_number }}
          kubectl set image deployments/server-deployment server=natwimt/mutli-server:${{ github.run_number }}
          kubectl set image deployments/worker-deployment worker=natwimt/mutli-worker:${{ github.run_number }}
